env_name: PongNoFrameskip-v4
network_arch: NatureCNN
minibatch_size: 32 
replay_memory_size: 100000
agent_history_length: 4 
target_network_update_frequency: 10000
discount_factor: 0.99
action_repeat: 4 
update_frequency: 4 
learning_rate: 0.00025 
gradient_momentum_alpha: 0.95 
min_squared_gradient_eps: 0.01 
initial_exploration: 1 
final_exploration: 0.1 
replay_start_size: 50000
no_op_max: 30 




# Run specific params
tb_log_dir: Breakout/Breakout_exp1            # MAKE SURE TO CHANGE THIS !!!!!!!!!
num_episodes: 30000